import 'product.dart';

class MyProducts {
  static List<Product> allProducts = [
    Product(
        id: 1,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/1.png',
        description: 'the best phone for 2024',
        price: 200,
        quantity: 1),
    Product(
        id: 6,
        name: 'galaxy',
        category: 'trending',
        image: 'images/iphone/6.png',
        description: 'the best phone for 2024',
        price: 290,
        quantity: 1),
    Product(
        id: 2,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/2.png',
        description: 'the best phone for 2024',
        price: 220,
        quantity: 1),
    Product(
        id: 3,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/3.png',
        description: 'the best phone for 2024',
        price: 310,
        quantity: 1),
    Product(
        id: 4,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/4.png',
        description: 'the best phone for 2024',
        price: 250,
        quantity: 1),
    Product(
        id: 5,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/5.png',
        description: 'the best phone for 2024',
        price: 259,
        quantity: 1),
    Product(
        id: 6,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/6.png',
        description: 'the best phone for 2024',
        price: 199,
        quantity: 1),
    Product(
        id: 7,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/7.png',
        description: 'the best phone for 2024',
        price: 224,
        quantity: 1),
    Product(
        id: 8,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/8.png',
        description: 'the best phone for 2024',
        price: 270,
        quantity: 1),
    Product(
        id: 9,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/9.png',
        description: 'the best phone for 2024',
        price: 330,
        quantity: 1),
    Product(
        id: 10,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/10.png',
        description: 'the best phone for 2024',
        price: 360,
        quantity: 1),
  ];
  static List<Product> galaxy = [
    Product(
        id: 1,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/1.png',
        description: 'the best phone for 2024',
        price: 340,
        quantity: 1),
    Product(
        id: 2,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/2.png',
        description: 'the best phone for 2024',
        price: 410,
        quantity: 1),
    Product(
        id: 3,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/3.png',
        description: 'the best phone for 2024',
        price: 450,
        quantity: 1),
    Product(
        id: 4,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/4.png',
        description: 'the best phone for 2024',
        price: 399,
        quantity: 1),
    Product(
        id: 5,
        name: 'galaxy',
        category: 'trending',
        image: 'images/galaxy/5.png',
        description: 'the best phone for 2024',
        price: 215,
        quantity: 1),
  ];
  static List<Product> iphone = [
    Product(
        id: 1,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/6.png',
        description: 'the best phone for 2024',
        price: 333,
        quantity: 1),
    Product(
        id: 2,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/7.png',
        description: 'the best phone for 2024',
        price: 362,
        quantity: 1),
    Product(
        id: 3,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/8.png',
        description: 'the best phone for 2024',
        price: 322,
        quantity: 1),
    Product(
        id: 4,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/9.png',
        description: 'the best phone for 2024',
        price: 288,
        quantity: 1),
    Product(
        id: 5,
        name: 'iphone',
        category: 'trending',
        image: 'images/iphone/10.png',
        description: 'the best phone for 2024',
        price: 399,
        quantity: 1),
  ];
}
